M48
; DRILL file {KiCad (6.0.0)} date Tue Mar 29 21:45:31 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-29T21:45:31-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C0.2165
%
G90
G05
T1
X4.3022Y-3.2825
X5.0295Y-4.9626
X5.9547Y-4.9892
X6.8238Y-3.3819
T2
X5.5157Y-3.2746
T0
M30
